# Generated by Django 5.0.3 on 2024-06-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_free_text',
            field=models.CharField(default='Welcome to my profile', max_length=500),
        ),
    ]
